---@meta

---@enum (key) AllowW1
AllowW1 = {
	AllowW1_Never = 0,
	AllowW1_CoursesOnly = 1,
	AllowW1_Everywhere = 2
}

---@enum (key) AttractSoundFrequency
AttractSoundFrequency = {
	AttractSoundFrequency_Never = 0,
	AttractSoundFrequency_EveryTime = 1,
	AttractSoundFrequency_Every2Times = 2,
	AttractSoundFrequency_Every3Times = 3,
	AttractSoundFrequency_Every4Times = 4,
	AttractSoundFrequency_Every5Times = 5
}

---@enum (key) AutosyncType
AutosyncType = {
	AutosyncType_Off = 0,
	AutosyncType_Song = 1,
	AutosyncType_Machine = 2,
	AutosyncType_Tempo = 3
}

--- Blending Modes.
---@see Actor.blend
---@enum (key) BlendMode
BlendMode = {
	BlendMode_Normal = 0,
	BlendMode_Add = 1,
	BlendMode_Subtract = 2,
	BlendMode_Modulate = 3,
	BlendMode_CopySrc = 4,
	BlendMode_AlphaMask = 5,
	BlendMode_AlphaKnockOut = 6,
	BlendMode_AlphaMultiply = 7,
	BlendMode_WeightedMultiply = 8,
	BlendMode_InvertDest = 9,
	BlendMode_NoEffect = 10
}

---@enum (key) CoinMode
CoinMode = {
	CoinMode_Home = 0,
	CoinMode_Pay = 1,
	CoinMode_Free = 2
}

---@enum (key) ColorType
ColorType = {
	ColorType_Red = 0,
	ColorType_Green = 1,
	ColorType_Blue = 2,
	ColorType_Alpha = 3
}

---@enum (key) CourseSortOrders
CourseSortOrders = {
	CourseSortOrders_Preferred = 0,
	CourseSortOrders_Songs = 1,
	CourseSortOrders_Meter = 2,
	CourseSortOrders_MeterSum = 3,
	CourseSortOrders_MeterRank = 4,
}

---@enum (key) CourseType
CourseType = {
	CourseType_Nonstop = 0,
	CourseType_Oni = 1,
	CourseType_Endless = 2,
	CourseType_Survival = 3,
}

---@enum (key) CullMode
CullMode = {
	CullMode_Back = 0,
	CullMode_Front = 1,
	CullMode_FrontAndBack = 2,
	CullMode_None = 3,
}

---@enum DeviceButton
DeviceButton = {
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_space",
	"DeviceButton_!",
	"DeviceButton_\"",
	"DeviceButton_#",
	"DeviceButton_$",
	"DeviceButton_%",
	"DeviceButton_&amp;",
	"DeviceButton_&quot;",
	"DeviceButton_(",
	"DeviceButton_)",
	"DeviceButton_*",
	"DeviceButton_+",
	"DeviceButton_comma",
	"DeviceButton_-",
	"DeviceButton_period",
	"DeviceButton_/",
	"DeviceButton_0",
	"DeviceButton_1",
	"DeviceButton_2",
	"DeviceButton_3",
	"DeviceButton_4",
	"DeviceButton_5",
	"DeviceButton_6",
	"DeviceButton_7",
	"DeviceButton_8",
	"DeviceButton_9",
	"DeviceButton_colon",
	"DeviceButton_;",
	"DeviceButton_&gt;",
	"DeviceButton_=",
	"DeviceButton_&lt;",
	"DeviceButton_?",
	"DeviceButton_@",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_[",
	"DeviceButton_backslash",
	"DeviceButton_]",
	"DeviceButton_^",
	"DeviceButton__",
	"DeviceButton_`",
	"DeviceButton_a",
	"DeviceButton_b",
	"DeviceButton_c",
	"DeviceButton_d",
	"DeviceButton_e",
	"DeviceButton_f",
	"DeviceButton_g",
	"DeviceButton_h",
	"DeviceButton_i",
	"DeviceButton_j",
	"DeviceButton_k",
	"DeviceButton_l",
	"DeviceButton_m",
	"DeviceButton_n",
	"DeviceButton_o",
	"DeviceButton_p",
	"DeviceButton_q",
	"DeviceButton_r",
	"DeviceButton_s",
	"DeviceButton_t",
	"DeviceButton_u",
	"DeviceButton_v",
	"DeviceButton_w",
	"DeviceButton_x",
	"DeviceButton_y",
	"DeviceButton_z",
	"DeviceButton_{",
	"DeviceButton_|",
	"DeviceButton_}",
	"DeviceButton_~",
	"DeviceButton_delete",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_backspace",
	"DeviceButton_tab",
	"DeviceButton_enter",
	"DeviceButton_pause",
	"DeviceButton_escape",
	"DeviceButton_F1",
	"DeviceButton_F2",
	"DeviceButton_F3",
	"DeviceButton_F4",
	"DeviceButton_F5",
	"DeviceButton_F6",
	"DeviceButton_F7",
	"DeviceButton_F8",
	"DeviceButton_F9",
	"DeviceButton_F10",
	"DeviceButton_F11",
	"DeviceButton_F12",
	"DeviceButton_F13",
	"DeviceButton_F14",
	"DeviceButton_F15",
	"DeviceButton_F16",
	"DeviceButton_left ctrl",
	"DeviceButton_right ctrl",
	"DeviceButton_left shift",
	"DeviceButton_right shift",
	"DeviceButton_left alt",
	"DeviceButton_right alt",
	"DeviceButton_left meta",
	"DeviceButton_right meta",
	"DeviceButton_left super",
	"DeviceButton_right super",
	"DeviceButton_menu",
	"DeviceButton_function",
	"DeviceButton_num lock",
	"DeviceButton_scroll lock",
	"DeviceButton_caps lock",
	"DeviceButton_prtsc",
	"DeviceButton_up",
	"DeviceButton_down",
	"DeviceButton_left",
	"DeviceButton_right",
	"DeviceButton_insert",
	"DeviceButton_home",
	"DeviceButton_end",
	"DeviceButton_pgup",
	"DeviceButton_pgdn",
	"DeviceButton_KP 0",
	"DeviceButton_KP 1",
	"DeviceButton_KP 2",
	"DeviceButton_KP 3",
	"DeviceButton_KP 4",
	"DeviceButton_KP 5",
	"DeviceButton_KP 6",
	"DeviceButton_KP 7",
	"DeviceButton_KP 8",
	"DeviceButton_KP 9",
	"DeviceButton_KP /",
	"DeviceButton_KP *",
	"DeviceButton_KP -",
	"DeviceButton_KP +",
	"DeviceButton_KP .",
	"DeviceButton_KP =",
	"DeviceButton_KP enter",
	"DeviceButton_unknown",
	"DeviceButton_oem101",
	"DeviceButton_oem102",
	"DeviceButton_unk 0",
	"DeviceButton_unk 1",
	"DeviceButton_unk 2",
	"DeviceButton_unk 3",
	"DeviceButton_unk 4",
	"DeviceButton_unk 5",
	"DeviceButton_unk 6",
	"DeviceButton_unk 7",
	"DeviceButton_unk 8",
	"DeviceButton_unk 9",
	"DeviceButton_unk 10",
	"DeviceButton_unk 11",
	"DeviceButton_unk 12",
	"DeviceButton_unk 13",
	"DeviceButton_unk 14",
	"DeviceButton_unk 15",
	"DeviceButton_unk 16",
	"DeviceButton_unk 17",
	"DeviceButton_unk 18",
	"DeviceButton_unk 19",
	"DeviceButton_unk 20",
	"DeviceButton_unk 21",
	"DeviceButton_unk 22",
	"DeviceButton_unk 23",
	"DeviceButton_unk 24",
	"DeviceButton_unk 25",
	"DeviceButton_unk 26",
	"DeviceButton_unk 27",
	"DeviceButton_unk 28",
	"DeviceButton_unk 29",
	"DeviceButton_unk 30",
	"DeviceButton_unk 31",
	"DeviceButton_unk 32",
	"DeviceButton_unk 33",
	"DeviceButton_unk 34",
	"DeviceButton_unk 35",
	"DeviceButton_unk 36",
	"DeviceButton_unk 37",
	"DeviceButton_unk 38",
	"DeviceButton_unk 39",
	"DeviceButton_unk 40",
	"DeviceButton_unk 41",
	"DeviceButton_unk 42",
	"DeviceButton_unk 43",
	"DeviceButton_unk 44",
	"DeviceButton_unk 45",
	"DeviceButton_unk 46",
	"DeviceButton_unk 47",
	"DeviceButton_unk 48",
	"DeviceButton_unk 49",
	"DeviceButton_unk 50",
	"DeviceButton_unk 51",
	"DeviceButton_unk 52",
	"DeviceButton_unk 53",
	"DeviceButton_unk 54",
	"DeviceButton_unk 55",
	"DeviceButton_unk 56",
	"DeviceButton_unk 57",
	"DeviceButton_unk 58",
	"DeviceButton_unk 59",
	"DeviceButton_unk 60",
	"DeviceButton_unk 61",
	"DeviceButton_unk 62",
	"DeviceButton_unk 63",
	"DeviceButton_unk 64",
	"DeviceButton_unk 65",
	"DeviceButton_unk 66",
	"DeviceButton_unk 67",
	"DeviceButton_unk 68",
	"DeviceButton_unk 69",
	"DeviceButton_unk 70",
	"DeviceButton_unk 71",
	"DeviceButton_unk 72",
	"DeviceButton_unk 73",
	"DeviceButton_unk 74",
	"DeviceButton_unk 75",
	"DeviceButton_unk 76",
	"DeviceButton_unk 77",
	"DeviceButton_unk 78",
	"DeviceButton_unk 79",
	"DeviceButton_unk 80",
	"DeviceButton_unk 81",
	"DeviceButton_unk 82",
	"DeviceButton_unk 83",
	"DeviceButton_unk 84",
	"DeviceButton_unk 85",
	"DeviceButton_unk 86",
	"DeviceButton_unk 87",
	"DeviceButton_unk 88",
	"DeviceButton_unk 89",
	"DeviceButton_unk 90",
	"DeviceButton_unk 91",
	"DeviceButton_unk 92",
	"DeviceButton_unk 93",
	"DeviceButton_unk 94",
	"DeviceButton_unk 95",
	"DeviceButton_unk 96",
	"DeviceButton_unk 97",
	"DeviceButton_unk 98",
	"DeviceButton_unk 99",
	"DeviceButton_unk 100",
	"DeviceButton_unk 101",
	"DeviceButton_unk 102",
	"DeviceButton_unk 103",
	"DeviceButton_unk 104",
	"DeviceButton_unk 105",
	"DeviceButton_unk 106",
	"DeviceButton_unk 107",
	"DeviceButton_unk 108",
	"DeviceButton_unk 109",
	"DeviceButton_unk 110",
	"DeviceButton_unk 111",
	"DeviceButton_unk 112",
	"DeviceButton_unk 113",
	"DeviceButton_unk 114",
	"DeviceButton_unk 115",
	"DeviceButton_unk 116",
	"DeviceButton_unk 117",
	"DeviceButton_unk 118",
	"DeviceButton_unk 119",
	"DeviceButton_unk 120",
	"DeviceButton_unk 121",
	"DeviceButton_unk 122",
	"DeviceButton_unk 123",
	"DeviceButton_unk 124",
	"DeviceButton_unk 125",
	"DeviceButton_unk 126",
	"DeviceButton_unk 127",
	"DeviceButton_unk 128",
	"DeviceButton_unk 129",
	"DeviceButton_unk 130",
	"DeviceButton_unk 131",
	"DeviceButton_unk 132",
	"DeviceButton_unk 133",
	"DeviceButton_unk 134",
	"DeviceButton_unk 135",
	"DeviceButton_unk 136",
	"DeviceButton_unk 137",
	"DeviceButton_unk 138",
	"DeviceButton_unk 139",
	"DeviceButton_unk 140",
	"DeviceButton_unk 141",
	"DeviceButton_unk 142",
	"DeviceButton_unk 143",
	"DeviceButton_unk 144",
	"DeviceButton_unk 145",
	"DeviceButton_unk 146",
	"DeviceButton_unk 147",
	"DeviceButton_unk 148",
	"DeviceButton_unk 149",
	"DeviceButton_unk 150",
	"DeviceButton_unk 151",
	"DeviceButton_unk 152",
	"DeviceButton_unk 153",
	"DeviceButton_unk 154",
	"DeviceButton_unk 155",
	"DeviceButton_unk 156",
	"DeviceButton_unk 157",
	"DeviceButton_unk 158",
	"DeviceButton_unk 159",
	"DeviceButton_unk 160",
	"DeviceButton_unk 161",
	"DeviceButton_unk 162",
	"DeviceButton_unk 163",
	"DeviceButton_unk 164",
	"DeviceButton_unk 165",
	"DeviceButton_unk 166",
	"DeviceButton_unk 167",
	"DeviceButton_unk 168",
	"DeviceButton_unk 169",
	"DeviceButton_unk 170",
	"DeviceButton_unk 171",
	"DeviceButton_unk 172",
	"DeviceButton_unk 173",
	"DeviceButton_unk 174",
	"DeviceButton_unk 175",
	"DeviceButton_unk 176",
	"DeviceButton_unk 177",
	"DeviceButton_unk 178",
	"DeviceButton_unk 179",
	"DeviceButton_unk 180",
	"DeviceButton_unk 181",
	"DeviceButton_unk 182",
	"DeviceButton_unk 183",
	"DeviceButton_unk 184",
	"DeviceButton_unk 185",
	"DeviceButton_unk 186",
	"DeviceButton_unk 187",
	"DeviceButton_unk 188",
	"DeviceButton_unk 189",
	"DeviceButton_unk 190",
	"DeviceButton_unk 191",
	"DeviceButton_unk 192",
	"DeviceButton_unk 193",
	"DeviceButton_unk 194",
	"DeviceButton_unk 195",
	"DeviceButton_unk 196",
	"DeviceButton_unk 197",
	"DeviceButton_unk 198",
	"DeviceButton_unk 199",
	"DeviceButton_unk 200",
	"DeviceButton_unk 201",
	"DeviceButton_unk 202",
	"DeviceButton_unk 203",
	"DeviceButton_unk 204",
	"DeviceButton_unk 205",
	"DeviceButton_unk 206",
	"DeviceButton_unk 207",
	"DeviceButton_unk 208",
	"DeviceButton_unk 209",
	"DeviceButton_unk 210",
	"DeviceButton_unk 211",
	"DeviceButton_unk 212",
	"DeviceButton_unk 213",
	"DeviceButton_unk 214",
	"DeviceButton_unk 215",
	"DeviceButton_unk 216",
	"DeviceButton_unk 217",
	"DeviceButton_unk 218",
	"DeviceButton_unk 219",
	"DeviceButton_unk 220",
	"DeviceButton_unk 221",
	"DeviceButton_unk 222",
	"DeviceButton_unk 223",
	"DeviceButton_unk 224",
	"DeviceButton_unk 225",
	"DeviceButton_unk 226",
	"DeviceButton_unk 227",
	"DeviceButton_unk 228",
	"DeviceButton_unk 229",
	"DeviceButton_unk 230",
	"DeviceButton_unk 231",
	"DeviceButton_unk 232",
	"DeviceButton_unk 233",
	"DeviceButton_unk 234",
	"DeviceButton_unk 235",
	"DeviceButton_unk 236",
	"DeviceButton_unk 237",
	"DeviceButton_unk 238",
	"DeviceButton_unk 239",
	"DeviceButton_unk 240",
	"DeviceButton_unk 241",
	"DeviceButton_unk 242",
	"DeviceButton_unk 243",
	"DeviceButton_unk 244",
	"DeviceButton_unk 245",
	"DeviceButton_unk 246",
	"DeviceButton_unk 247",
	"DeviceButton_unk 248",
	"DeviceButton_unk 249",
	"DeviceButton_unk 250",
	"DeviceButton_unk 251",
	"DeviceButton_unk 252",
	"DeviceButton_unk 253",
	"DeviceButton_unk 254",
	"DeviceButton_unk 255",
	"DeviceButton_unk 256",
	"DeviceButton_unk 257",
	"DeviceButton_unk 258",
	"DeviceButton_unk 259",
	"DeviceButton_unk 260",
	"DeviceButton_unk 261",
	"DeviceButton_unk 262",
	"DeviceButton_unk 263",
	"DeviceButton_unk 264",
	"DeviceButton_unk 265",
	"DeviceButton_unk 266",
	"DeviceButton_unk 267",
	"DeviceButton_unk 268",
	"DeviceButton_unk 269",
	"DeviceButton_unk 270",
	"DeviceButton_unk 271",
	"DeviceButton_unk 272",
	"DeviceButton_unk 273",
	"DeviceButton_unk 274",
	"DeviceButton_unk 275",
	"DeviceButton_unk 276",
	"DeviceButton_unknown",
	"DeviceButton_Left Axis Left",
	"DeviceButton_Left Axis Right",
	"DeviceButton_Left Axis Up",
	"DeviceButton_Left Axis Down",
	"DeviceButton_Right Axis Left",
	"DeviceButton_Right Axis Right",
	"DeviceButton_Right Axis Up",
	"DeviceButton_Right Axis Down",
	"DeviceButton_Left Trigger",
	"DeviceButton_Right Trigger",
	"DeviceButton_Button A",
	"DeviceButton_Button B",
	"DeviceButton_Button X",
	"DeviceButton_Button Y",
	"DeviceButton_Back",
	"DeviceButton_Guide",
	"DeviceButton_Start",
	"DeviceButton_LeftStick",
	"DeviceButton_RightStick",
	"DeviceButton_LeftShoulder",
	"DeviceButton_RightShoulder",
	"DeviceButton_DPad Up",
	"DeviceButton_DPad Down",
	"DeviceButton_DPad Left",
	"DeviceButton_Dpad Right",
	"DeviceButton_Left1",
	"DeviceButton_Right1",
	"DeviceButton_Up1",
	"DeviceButton_Down1",
	"DeviceButton_Left2",
	"DeviceButton_Right2",
	"DeviceButton_Up2",
	"DeviceButton_Down2",
	"DeviceButton_Z-Up",
	"DeviceButton_Z-Down",
	"DeviceButton_R-Up",
	"DeviceButton_R-Down",
	"DeviceButton_R-Left",
	"DeviceButton_R-Right",
	"DeviceButton_ZR-Up",
	"DeviceButton_ZR-Down",
	"DeviceButton_H-Left",
	"DeviceButton_H-Right",
	"DeviceButton_H-Up",
	"DeviceButton_H-Down",
	"DeviceButton_Aux1",
	"DeviceButton_Aux2",
	"DeviceButton_Aux3",
	"DeviceButton_Aux4",
	"DeviceButton_Button 1",
	"DeviceButton_Button 2",
	"DeviceButton_Button 3",
	"DeviceButton_Button 4",
	"DeviceButton_Button 5",
	"DeviceButton_Button 6",
	"DeviceButton_Button 7",
	"DeviceButton_Button 8",
	"DeviceButton_Button 9",
	"DeviceButton_Button 10",
	"DeviceButton_Button 11",
	"DeviceButton_Button 12",
	"DeviceButton_Button 13",
	"DeviceButton_Button 14",
	"DeviceButton_Button 15",
	"DeviceButton_Button 16",
	"DeviceButton_Button 17",
	"DeviceButton_Button 18",
	"DeviceButton_Button 19",
	"DeviceButton_Button 20",
	"DeviceButton_Button 21",
	"DeviceButton_Button 22",
	"DeviceButton_Button 23",
	"DeviceButton_Button 24",
	"DeviceButton_Button 25",
	"DeviceButton_Button 26",
	"DeviceButton_Button 27",
	"DeviceButton_Button 28",
	"DeviceButton_Button 29",
	"DeviceButton_Button 30",
	"DeviceButton_Button 31",
	"DeviceButton_Button 32",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_Midi Button 0",
	"DeviceButton_Midi Button 1",
	"DeviceButton_Midi Button 2",
	"DeviceButton_Midi Button 3",
	"DeviceButton_Midi Button 4",
	"DeviceButton_Midi Button 5",
	"DeviceButton_Midi Button 6",
	"DeviceButton_Midi Button 7",
	"DeviceButton_Midi Button 8",
	"DeviceButton_Midi Button 9",
	"DeviceButton_Midi Button 10",
	"DeviceButton_Midi Button 11",
	"DeviceButton_Midi Button 12",
	"DeviceButton_Midi Button 13",
	"DeviceButton_Midi Button 14",
	"DeviceButton_Midi Button 15",
	"DeviceButton_Midi Button 16",
	"DeviceButton_Midi Button 17",
	"DeviceButton_Midi Button 18",
	"DeviceButton_Midi Button 19",
	"DeviceButton_Midi Button 20",
	"DeviceButton_Midi Button 21",
	"DeviceButton_Midi Button 22",
	"DeviceButton_Midi Button 23",
	"DeviceButton_Midi Button 24",
	"DeviceButton_Midi Button 25",
	"DeviceButton_Midi Button 26",
	"DeviceButton_Midi Button 27",
	"DeviceButton_Midi Button 28",
	"DeviceButton_Midi Button 29",
	"DeviceButton_Midi Button 30",
	"DeviceButton_Midi Button 31",
	"DeviceButton_Midi Button 32",
	"DeviceButton_Midi Button 33",
	"DeviceButton_Midi Button 34",
	"DeviceButton_Midi Button 35",
	"DeviceButton_Midi Button 36",
	"DeviceButton_Midi Button 37",
	"DeviceButton_Midi Button 38",
	"DeviceButton_Midi Button 39",
	"DeviceButton_Midi Button 40",
	"DeviceButton_Midi Button 41",
	"DeviceButton_Midi Button 42",
	"DeviceButton_Midi Button 43",
	"DeviceButton_Midi Button 44",
	"DeviceButton_Midi Button 45",
	"DeviceButton_Midi Button 46",
	"DeviceButton_Midi Button 47",
	"DeviceButton_Midi Button 48",
	"DeviceButton_Midi Button 49",
	"DeviceButton_Midi Button 50",
	"DeviceButton_Midi Button 51",
	"DeviceButton_Midi Button 52",
	"DeviceButton_Midi Button 53",
	"DeviceButton_Midi Button 54",
	"DeviceButton_Midi Button 55",
	"DeviceButton_Midi Button 56",
	"DeviceButton_Midi Button 57",
	"DeviceButton_Midi Button 58",
	"DeviceButton_Midi Button 59",
	"DeviceButton_Midi Button 60",
	"DeviceButton_Midi Button 61",
	"DeviceButton_Midi Button 62",
	"DeviceButton_Midi Button 63",
	"DeviceButton_Midi Button 64",
	"DeviceButton_Midi Button 65",
	"DeviceButton_Midi Button 66",
	"DeviceButton_Midi Button 67",
	"DeviceButton_Midi Button 68",
	"DeviceButton_Midi Button 69",
	"DeviceButton_Midi Button 70",
	"DeviceButton_Midi Button 71",
	"DeviceButton_Midi Button 72",
	"DeviceButton_Midi Button 73",
	"DeviceButton_Midi Button 74",
	"DeviceButton_Midi Button 75",
	"DeviceButton_Midi Button 76",
	"DeviceButton_Midi Button 77",
	"DeviceButton_Midi Button 78",
	"DeviceButton_Midi Button 79",
	"DeviceButton_Midi Button 80",
	"DeviceButton_Midi Button 81",
	"DeviceButton_Midi Button 82",
	"DeviceButton_Midi Button 83",
	"DeviceButton_Midi Button 84",
	"DeviceButton_Midi Button 85",
	"DeviceButton_Midi Button 86",
	"DeviceButton_Midi Button 87",
	"DeviceButton_Midi Button 88",
	"DeviceButton_Midi Button 89",
	"DeviceButton_Midi Button 90",
	"DeviceButton_Midi Button 91",
	"DeviceButton_Midi Button 92",
	"DeviceButton_Midi Button 93",
	"DeviceButton_Midi Button 94",
	"DeviceButton_Midi Button 95",
	"DeviceButton_Midi Button 96",
	"DeviceButton_Midi Button 97",
	"DeviceButton_Midi Button 98",
	"DeviceButton_Midi Button 99",
	"DeviceButton_Midi Button 100",
	"DeviceButton_Midi Button 101",
	"DeviceButton_Midi Button 102",
	"DeviceButton_Midi Button 103",
	"DeviceButton_Midi Button 104",
	"DeviceButton_Midi Button 105",
	"DeviceButton_Midi Button 106",
	"DeviceButton_Midi Button 107",
	"DeviceButton_Midi Button 108",
	"DeviceButton_Midi Button 109",
	"DeviceButton_Midi Button 110",
	"DeviceButton_Midi Button 111",
	"DeviceButton_Midi Button 112",
	"DeviceButton_Midi Button 113",
	"DeviceButton_Midi Button 114",
	"DeviceButton_Midi Button 115",
	"DeviceButton_Midi Button 116",
	"DeviceButton_Midi Button 117",
	"DeviceButton_Midi Button 118",
	"DeviceButton_Midi Button 119",
	"DeviceButton_Midi Button 120",
	"DeviceButton_Midi Button 121",
	"DeviceButton_Midi Button 122",
	"DeviceButton_Midi Button 123",
	"DeviceButton_Midi Button 124",
	"DeviceButton_Midi Button 125",
	"DeviceButton_Midi Button 126",
	"DeviceButton_Midi Button 127",
	"DeviceButton_Midi Button 128",
	"DeviceButton_Midi Button 129",
	"DeviceButton_Midi Button 130",
	"DeviceButton_Midi Button 131",
	"DeviceButton_Midi Button 132",
	"DeviceButton_Midi Button 133",
	"DeviceButton_Midi Button 134",
	"DeviceButton_Midi Button 135",
	"DeviceButton_Midi Button 136",
	"DeviceButton_Midi Button 137",
	"DeviceButton_Midi Button 138",
	"DeviceButton_Midi Button 139",
	"DeviceButton_Midi Button 140",
	"DeviceButton_Midi Button 141",
	"DeviceButton_Midi Button 142",
	"DeviceButton_Midi Button 143",
	"DeviceButton_Midi Button 144",
	"DeviceButton_Midi Button 145",
	"DeviceButton_Midi Button 146",
	"DeviceButton_Midi Button 147",
	"DeviceButton_Midi Button 148",
	"DeviceButton_Midi Button 149",
	"DeviceButton_Midi Button 150",
	"DeviceButton_Midi Button 151",
	"DeviceButton_Midi Button 152",
	"DeviceButton_Midi Button 153",
	"DeviceButton_Midi Button 154",
	"DeviceButton_Midi Button 155",
	"DeviceButton_Midi Button 156",
	"DeviceButton_Midi Button 157",
	"DeviceButton_Midi Button 158",
	"DeviceButton_Midi Button 159",
	"DeviceButton_Midi Button 160",
	"DeviceButton_Midi Button 161",
	"DeviceButton_Midi Button 162",
	"DeviceButton_Midi Button 163",
	"DeviceButton_Midi Button 164",
	"DeviceButton_Midi Button 165",
	"DeviceButton_Midi Button 166",
	"DeviceButton_Midi Button 167",
	"DeviceButton_Midi Button 168",
	"DeviceButton_Midi Button 169",
	"DeviceButton_Midi Button 170",
	"DeviceButton_Midi Button 171",
	"DeviceButton_Midi Button 172",
	"DeviceButton_Midi Button 173",
	"DeviceButton_Midi Button 174",
	"DeviceButton_Midi Button 175",
	"DeviceButton_Midi Button 176",
	"DeviceButton_Midi Button 177",
	"DeviceButton_Midi Button 178",
	"DeviceButton_Midi Button 179",
	"DeviceButton_Midi Button 180",
	"DeviceButton_Midi Button 181",
	"DeviceButton_Midi Button 182",
	"DeviceButton_Midi Button 183",
	"DeviceButton_Midi Button 184",
	"DeviceButton_Midi Button 185",
	"DeviceButton_Midi Button 186",
	"DeviceButton_Midi Button 187",
	"DeviceButton_Midi Button 188",
	"DeviceButton_Midi Button 189",
	"DeviceButton_Midi Button 190",
	"DeviceButton_Midi Button 191",
	"DeviceButton_Midi Button 192",
	"DeviceButton_Midi Button 193",
	"DeviceButton_Midi Button 194",
	"DeviceButton_Midi Button 195",
	"DeviceButton_Midi Button 196",
	"DeviceButton_Midi Button 197",
	"DeviceButton_Midi Button 198",
	"DeviceButton_Midi Button 199",
	"DeviceButton_Midi Extra 0",
	"DeviceButton_Midi Extra 1",
	"DeviceButton_Midi Extra 2",
	"DeviceButton_Midi Extra 3",
	"DeviceButton_Midi Extra 4",
	"DeviceButton_Midi Extra 5",
	"DeviceButton_Midi Extra 6",
	"DeviceButton_Midi Extra 7",
	"DeviceButton_Midi Extra 8",
	"DeviceButton_Midi Extra 9",
	"DeviceButton_Midi Extra 10",
	"DeviceButton_Midi Extra 11",
	"DeviceButton_Midi Extra 12",
	"DeviceButton_Midi Extra 13",
	"DeviceButton_Midi Extra 14",
	"DeviceButton_Midi Extra 15",
	"DeviceButton_Midi Extra 16",
	"DeviceButton_Midi Extra 17",
	"DeviceButton_Midi Extra 18",
	"DeviceButton_Midi Extra 19",
	"DeviceButton_Midi Extra 20",
	"DeviceButton_Midi Extra 21",
	"DeviceButton_Midi Extra 22",
	"DeviceButton_Midi Extra 23",
	"DeviceButton_Midi Extra 24",
	"DeviceButton_Midi Extra 25",
	"DeviceButton_Midi Extra 26",
	"DeviceButton_Midi Extra 27",
	"DeviceButton_Midi Extra 28",
	"DeviceButton_Midi Extra 29",
	"DeviceButton_Midi Extra 30",
	"DeviceButton_Midi Extra 31",
	"DeviceButton_Midi Extra 32",
	"DeviceButton_Midi Extra 33",
	"DeviceButton_Midi Extra 34",
	"DeviceButton_Midi Extra 35",
	"DeviceButton_Midi Extra 36",
	"DeviceButton_Midi Extra 37",
	"DeviceButton_Midi Extra 38",
	"DeviceButton_Midi Extra 39",
	"DeviceButton_Midi Extra 40",
	"DeviceButton_Midi Extra 41",
	"DeviceButton_Midi Extra 42",
	"DeviceButton_Midi Extra 43",
	"DeviceButton_Midi Extra 44",
	"DeviceButton_Midi Extra 45",
	"DeviceButton_Midi Extra 46",
	"DeviceButton_Midi Extra 47",
	"DeviceButton_Midi Extra 48",
	"DeviceButton_Midi Extra 49",
	"DeviceButton_Midi Extra 50",
	"DeviceButton_Midi Extra 51",
	"DeviceButton_Midi Extra 52",
	"DeviceButton_Midi Extra 53",
	"DeviceButton_Midi Extra 54",
	"DeviceButton_Midi Extra 55",
	"DeviceButton_Midi Extra 56",
	"DeviceButton_Midi Extra 57",
	"DeviceButton_Midi Extra 58",
	"DeviceButton_Midi Extra 59",
	"DeviceButton_Midi Extra 60",
	"DeviceButton_Midi Extra 61",
	"DeviceButton_Midi Extra 62",
	"DeviceButton_Midi Extra 63",
	"DeviceButton_Midi Extra 64",
	"DeviceButton_Midi Extra 65",
	"DeviceButton_Midi Extra 66",
	"DeviceButton_Midi Extra 67",
	"DeviceButton_Midi Extra 68",
	"DeviceButton_Midi Extra 69",
	"DeviceButton_Midi Extra 70",
	"DeviceButton_Midi Extra 71",
	"DeviceButton_Midi Extra 72",
	"DeviceButton_Midi Extra 73",
	"DeviceButton_Midi Extra 74",
	"DeviceButton_Midi Extra 75",
	"DeviceButton_Midi Extra 76",
	"DeviceButton_Midi Extra 77",
	"DeviceButton_Midi Extra 78",
	"DeviceButton_Midi Extra 79",
	"DeviceButton_Midi Extra 80",
	"DeviceButton_Midi Extra 81",
	"DeviceButton_Midi Extra 82",
	"DeviceButton_Midi Extra 83",
	"DeviceButton_Midi Extra 84",
	"DeviceButton_Midi Extra 85",
	"DeviceButton_Midi Extra 86",
	"DeviceButton_Midi Extra 87",
	"DeviceButton_Midi Extra 88",
	"DeviceButton_Midi Extra 89",
	"DeviceButton_Midi Extra 90",
	"DeviceButton_Midi Extra 91",
	"DeviceButton_Midi Extra 92",
	"DeviceButton_Midi Extra 93",
	"DeviceButton_Midi Extra 94",
	"DeviceButton_Midi Extra 95",
	"DeviceButton_Midi Extra 96",
	"DeviceButton_Midi Extra 97",
	"DeviceButton_Midi Extra 98",
	"DeviceButton_Midi Extra 99",
	"DeviceButton_Midi Extra 100",
	"DeviceButton_Midi Extra 101",
	"DeviceButton_Midi Extra 102",
	"DeviceButton_Midi Extra 103",
	"DeviceButton_Midi Extra 104",
	"DeviceButton_Midi Extra 105",
	"DeviceButton_Midi Extra 106",
	"DeviceButton_Midi Extra 107",
	"DeviceButton_Midi Extra 108",
	"DeviceButton_Midi Extra 109",
	"DeviceButton_Midi Extra 110",
	"DeviceButton_Midi Extra 111",
	"DeviceButton_Midi Extra 112",
	"DeviceButton_Midi Extra 113",
	"DeviceButton_Midi Extra 114",
	"DeviceButton_Midi Extra 115",
	"DeviceButton_Midi Extra 116",
	"DeviceButton_Midi Extra 117",
	"DeviceButton_Midi Extra 118",
	"DeviceButton_Midi Extra 119",
	"DeviceButton_Midi Extra 120",
	"DeviceButton_Midi Extra 121",
	"DeviceButton_Midi Extra 122",
	"DeviceButton_Midi Extra 123",
	"DeviceButton_Midi Extra 124",
	"DeviceButton_Midi Extra 125",
	"DeviceButton_Midi Extra 126",
	"DeviceButton_Midi Extra 127",
	"DeviceButton_Midi Extra 128",
	"DeviceButton_Midi Extra 129",
	"DeviceButton_Midi Extra 130",
	"DeviceButton_Midi Extra 131",
	"DeviceButton_Midi Extra 132",
	"DeviceButton_Midi Extra 133",
	"DeviceButton_Midi Extra 134",
	"DeviceButton_Midi Extra 135",
	"DeviceButton_Midi Extra 136",
	"DeviceButton_Midi Extra 137",
	"DeviceButton_Midi Extra 138",
	"DeviceButton_Midi Extra 139",
	"DeviceButton_Midi Extra 140",
	"DeviceButton_Midi Extra 141",
	"DeviceButton_Midi Extra 142",
	"DeviceButton_Midi Extra 143",
	"DeviceButton_Midi Extra 144",
	"DeviceButton_Midi Extra 145",
	"DeviceButton_Midi Extra 146",
	"DeviceButton_Midi Extra 147",
	"DeviceButton_Midi Extra 148",
	"DeviceButton_Midi Extra 149",
	"DeviceButton_Midi Extra 150",
	"DeviceButton_Midi Extra 151",
	"DeviceButton_Midi Extra 152",
	"DeviceButton_Midi Extra 153",
	"DeviceButton_Midi Extra 154",
	"DeviceButton_Midi Extra 155",
	"DeviceButton_Midi Extra 156",
	"DeviceButton_Midi Extra 157",
	"DeviceButton_Midi Extra 158",
	"DeviceButton_Midi Extra 159",
	"DeviceButton_Midi Extra 160",
	"DeviceButton_Midi Extra 161",
	"DeviceButton_Midi Extra 162",
	"DeviceButton_Midi Extra 163",
	"DeviceButton_Midi Extra 164",
	"DeviceButton_Midi Extra 165",
	"DeviceButton_Midi Extra 166",
	"DeviceButton_Midi Extra 167",
	"DeviceButton_Midi Extra 168",
	"DeviceButton_Midi Extra 169",
	"DeviceButton_Midi Extra 170",
	"DeviceButton_Midi Extra 171",
	"DeviceButton_Midi Extra 172",
	"DeviceButton_Midi Extra 173",
	"DeviceButton_Midi Extra 174",
	"DeviceButton_Midi Extra 175",
	"DeviceButton_Midi Extra 176",
	"DeviceButton_Midi Extra 177",
	"DeviceButton_Midi Extra 178",
	"DeviceButton_Midi Extra 179",
	"DeviceButton_Midi Extra 180",
	"DeviceButton_Midi Extra 181",
	"DeviceButton_Midi Extra 182",
	"DeviceButton_Midi Extra 183",
	"DeviceButton_Midi Extra 184",
	"DeviceButton_Midi Extra 185",
	"DeviceButton_Midi Extra 186",
	"DeviceButton_Midi Extra 187",
	"DeviceButton_Midi Extra 188",
	"DeviceButton_Midi Extra 189",
	"DeviceButton_Midi Extra 190",
	"DeviceButton_Midi Extra 191",
	"DeviceButton_Midi Extra 192",
	"DeviceButton_Midi Extra 193",
	"DeviceButton_Midi Extra 194",
	"DeviceButton_Midi Extra 195",
	"DeviceButton_Midi Extra 196",
	"DeviceButton_Midi Extra 197",
	"DeviceButton_Midi Extra 198",
	"DeviceButton_Midi Extra 199",
	"DeviceButton_left (01)",
	"DeviceButton_right (02)",
	"DeviceButton_middle (03)",
	"DeviceButton_back (04)",
	"DeviceButton_forward (05)",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_wheel up",
	"DeviceButton_wheel down",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_reflex left",
	"DeviceButton_reflex down",
	"DeviceButton_reflex up",
	"DeviceButton_reflex right",
	"DeviceButton_reflex2 left",
	"DeviceButton_reflex2 down",
	"DeviceButton_reflex2 up",
	"DeviceButton_reflex2 right",
	"DeviceButton_unknown",
	"DeviceButton_unknown",
	"DeviceButton_smx left",
	"DeviceButton_smx upleft",
	"DeviceButton_smx up",
	"DeviceButton_smx upright",
	"DeviceButton_smx right",
	"DeviceButton_smx downright",
	"DeviceButton_smx down",
	"DeviceButton_smx downleft",
	"DeviceButton_smx center",
	"DeviceButton_unknown",
	"DeviceButton_smx2 left",
	"DeviceButton_smx2 upleft",
	"DeviceButton_smx2 up",
	"DeviceButton_smx2 upright",
	"DeviceButton_smx2 right",
	"DeviceButton_smx2 downright",
	"DeviceButton_smx2 down",
	"DeviceButton_smx2 downleft",
	"DeviceButton_smx2 center",
	"DeviceButton_unknown",
	"DeviceButton_finger 1",
	"DeviceButton_finger 2",
	"DeviceButton_finger 3",
	"DeviceButton_finger 4",
	"DeviceButton_finger 5",
	"DeviceButton_finger 6",
}

---@enum (key) Difficulty
Difficulty = {
	Difficulty_Beginner = 0,
	Difficulty_Easy = 1,
	Difficulty_Medium = 2,
	Difficulty_Hard = 3,
	Difficulty_Challenge = 4,
	Difficulty_Edit = 5,
	Difficulty_D7 = 6,
	Difficulty_D8 = 7,
	Difficulty_D9 = 8,
	Difficulty_D10 = 9,
	Difficulty_D11 = 10,
	Difficulty_D12 = 11,
	Difficulty_D13 = 12,
	Difficulty_D14 = 13,
	Difficulty_D15 = 14,
}

---@enum (key) DisplayBPM
DisplayBPM = {
	DisplayBPM_Actual = 0,
	DisplayBPM_Specified = 1,
	DisplayBPM_Random = 2,
}

---@enum (key) DrainType
DrainType = {
	DrainType_Normal = 0,
	DrainType_NoRecover = 1,
	DrainType_SuddenDeath = 2,
}

---@enum (key) DrawMode
DrawMode = {
	DrawMode_Quads = 0,
	DrawMode_QuadStrip = 1,
	DrawMode_Fan = 2,
	DrawMode_Strip = 3,
	DrawMode_Triangles = 4,
	DrawMode_LineStrip = 5,
	DrawMode_PolyLineStrip = 6,
	DrawMode_LineStripM = 7,
	DrawMode_SymmetricQuadStrip = 8,
	DrawMode_Points = 9,
	DrawMode_Lines = 10,
}

---@enum (key) EarnedExtraStage
EarnedExtraStage = {
	EarnedExtraStage_No = 0,
	EarnedExtraStage_Extra1 = 1,
	EarnedExtraStage_Extra2 = 2,
}

---@enum (key) EditMode
EditMode = {
	EditMode_Practice = 0,
	EditMode_CourseMods = 1,
	EditMode_Home = 2,
	EditMode_Full = 3,
}

---@enum (key) EditState
EditState = {
	EditState_Edit = 0,
	EditState_Record = 1,
	EditState_RecordPaused = 2,
	EditState_Playing = 3,
}

---@enum (key) EffectMode
EffectMode = {
	EffectMode_Normal = 0,
	EffectMode_Unpremultiply = 1,
	EffectMode_ColorBurn = 2,
	EffectMode_ColorDodge = 3,
	EffectMode_VividLight = 4,
	EffectMode_HardMix = 5,
	EffectMode_Overlay = 6,
	EffectMode_Screen = 7,
	EffectMode_YUV2RGB = 8,
	EffectMode_DistanceField = 9,
	EffectMode_AlphaBlack = 10,
}

---@enum (key) FailType
FailType = {
	FailType_Immediate = 0,
	FailType_ImmediateContinue = 1,
	FailType_EndOfSong = 2,
	FailType_Off = 3,
}

---@enum (key) FileType
FileType = {
	FileType_Bitmap = 0,
	FileType_Sprite = 1,
	FileType_Sound = 2,
	FileType_Movie = 3,
	FileType_Directory = 4,
	FileType_Xml = 5,
	FileType_Model = 6,
	FileType_Lua = 7,
	FileType_Ini = 8,
}

---@enum (key) GameController
GameController = {
	GameController_1 = 0,
	GameController_2 = 1,
}

---@enum (key) GetRankingName
GetRankingName = {
	GetRankingName_Off = 0,
	GetRankingName_On = 1,
	GetRankingName_List = 2,
}

---@enum (key) GoalType {
GoalType = {
	GoalType_Calories = 0,
	GoalType_Time = 1,
	GoalType_None = 2,
}

---@enum (key) Grade {
Grade = {
	Grade_Tier01 = 0,
	Grade_Tier02 = 1,
	Grade_Tier03 = 2,
	Grade_Tier04 = 3,
	Grade_Tier05 = 4,
	Grade_Tier06 = 5,
	Grade_Tier07 = 6,
	Grade_Tier08 = 7,
	Grade_Tier09 = 8,
	Grade_Tier10 = 9,
	Grade_Tier11 = 10,
	Grade_Tier12 = 11,
	Grade_Tier13 = 12,
	Grade_Tier14 = 13,
	Grade_Tier15 = 14,
	Grade_Tier16 = 15,
	Grade_Tier17 = 16,
	Grade_Tier18 = 17,
	Grade_Tier19 = 18,
	Grade_Tier20 = 19,
	Grade_Failed = 20,
}

---@enum (key) HealthState
HealthState = {
	HealthState_Hot = 0,
	HealthState_Alive = 1,
	HealthState_Danger = 2,
	HealthState_Dead = 3,
}

---@enum (key) HighResolutionTextures
HighResolutionTextures = {
	HighResolutionTextures_Auto = 0,
	HighResolutionTextures_ForceOff = 1,
	HighResolutionTextures_ForceOn = 2,
}

---@enum (key) HighScoresType
HighScoresType = {
	HighScoresType_AllSteps = 0,
	HighScoresType_NonstopCourses = 1,
	HighScoresType_OniCourses = 2,
	HighScoresType_SurvivalCourses = 3,
	HighScoresType_AllCourses = 4,
}

---@enum (key) HoldNoteScore
HoldNoteScore = {
	HoldNoteScore_None = 0,
	HoldNoteScore_LetGo = 1,
	HoldNoteScore_Held = 2,
	HoldNoteScore_MissedHold = 3,
}

--- Horizontal alignment.
---@see Actor.horizalign
---@enum (key) HorizAlign
HorizAlign = {
	HorizAlign_Left = 0,
	HorizAlign_Center = 1,
	HorizAlign_Right = 2
}

---@enum (key) ImageCacheMode
ImageCacheMode = {
	ImageCacheMode_Off = 0,
	ImageCacheMode_LowResPreload = 1,
	ImageCacheMode_LowResLoadOnDemand = 2,
	ImageCacheMode_Full = 3,
}

---@enum (key) InputDevice
InputDevice = {
	InputDevice_Key = 0,
	InputDevice_Joy1 = 1,
	InputDevice_Joy2 = 2,
	InputDevice_Joy3 = 3,
	InputDevice_Joy4 = 4,
	InputDevice_Joy5 = 5,
	InputDevice_Joy6 = 6,
	InputDevice_Joy7 = 7,
	InputDevice_Joy8 = 8,
	InputDevice_Joy9 = 9,
	InputDevice_Joy10 = 10,
	InputDevice_Joy11 = 11,
	InputDevice_Joy12 = 12,
	InputDevice_Joy13 = 13,
	InputDevice_Joy14 = 14,
	InputDevice_Joy15 = 15,
	InputDevice_Joy16 = 16,
	InputDevice_Joy17 = 17,
	InputDevice_Joy18 = 18,
	InputDevice_Joy19 = 19,
	InputDevice_Joy20 = 20,
	InputDevice_Joy21 = 21,
	InputDevice_Joy22 = 22,
	InputDevice_Joy23 = 23,
	InputDevice_Joy24 = 24,
	InputDevice_Joy25 = 25,
	InputDevice_Joy26 = 26,
	InputDevice_Joy27 = 27,
	InputDevice_Joy28 = 28,
	InputDevice_Joy29 = 29,
	InputDevice_Joy30 = 30,
	InputDevice_Joy31 = 31,
	InputDevice_Joy32 = 32,
	InputDevice_Pump1 = 33,
	InputDevice_Pump2 = 34,
	InputDevice_Midi = 35,
	InputDevice_Mouse = 36,
	InputDevice_Touch = 37,
	InputDevice_PIUIO = 38,
	InputDevice_Reflex = 39,
	InputDevice_PortMidi = 40,
	InputDevice_Aux = 41,
}

---@enum (key) InputEventType
InputEventType = {
	InputEventType_FirstPress = 0,
	InputEventType_Repeat = 1,
	InputEventType_Release = 2,
}

---@enum (key) JudgmentLine
JudgmentLine = {
	JudgmentLine_W1 = 0,
	JudgmentLine_W2 = 1,
	JudgmentLine_W3 = 2,
	JudgmentLine_W4 = 3,
	JudgmentLine_W5 = 4,
	JudgmentLine_Miss = 5,
	JudgmentLine_Held = 6,
	JudgmentLine_MaxCombo = 7,
}

---@enum (key) LayoutType
LayoutType = {
	LayoutType_ShowAllInRow = 0,
	LayoutType_ShowOneInRow = 1,
}

---@enum (key) LifeType
LifeType = {
	LifeType_Bar = 0,
	LifeType_Battery = 1,
	LifeType_Time = 2,
}

---@enum (key) LightsMode
LightsMode = {
	LightsMode_Attract = 0,
	LightsMode_Joining = 1,
	LightsMode_MenuStartOnly = 2,
	LightsMode_MenuStartAndDirections = 3,
	LightsMode_Demonstration = 4,
	LightsMode_Gameplay = 5,
	LightsMode_Stage = 6,
	LightsMode_Cleared = 7,
	LightsMode_TestAutoCycle = 8,
	LightsMode_TestManualCycle = 9,
}

---@enum (key) Maybe
Maybe = {
	Maybe_Ask = 0,
	Maybe_No = 1,
	Maybe_Yes = 2,
}

---@enum (key) MemoryCardDriverType
MemoryCardDriverType = {
	MemoryCardDriverType_USB = 0,
	MemoryCardDriverType_Directory = 1,
}

---@enum (key) MemoryCardState
MemoryCardState = {
	MemoryCardState_ready = 0,
	MemoryCardState_checking = 1,
	MemoryCardState_late = 2,
	MemoryCardState_error = 3,
	MemoryCardState_removed = 4,
	MemoryCardState_none = 5,
}

---@enum (key) ModPlayerNumber
ModPlayerNumber = {
	ModPlayerNumber_P1 = 0,
	ModPlayerNumber_P2 = 1,
	ModPlayerNumber_P3 = 2,
	ModPlayerNumber_P4 = 3,
	ModPlayerNumber_P5 = 4,
	ModPlayerNumber_P6 = 5,
	ModPlayerNumber_P7 = 6,
	ModPlayerNumber_P8 = 7,
	ModPlayerNumber_P9 = 8,
	ModPlayerNumber_P10 = 9,
	ModPlayerNumber_P11 = 10,
	ModPlayerNumber_P12 = 11,
}

---@enum (key) ModsLevel
ModsLevel = {
	ModsLevel_Preferred = 0,
	ModsLevel_Stage = 1,
	ModsLevel_Song = 2,
	ModsLevel_Current = 3,
}

---@enum (key) ModSplineAxis
ModSplineAxis = {
	ModSplineAxis_X = 0,
	ModSplineAxis_Y = 1,
	ModSplineAxis_Z = 2,
	ModSplineAxis_RotX = 3,
	ModSplineAxis_RotY = 4,
	ModSplineAxis_RotZ = 5,
	ModSplineAxis_Zoom = 6,
	ModSplineAxis_SkewX = 7,
	ModSplineAxis_SkewY = 8,
	ModSplineAxis_Stealth = 9,
}

---@enum (key) ModSplineType
ModSplineType = {
	ModSplineType_Linear = 0,
	ModSplineType_Cosine = 1,
	ModSplineType_Cubic = 2,
}

---@enum (key) ModTimerType
ModTimerType = {
	ModTimerType_Game = 0,
	ModTimerType_Beat = 1,
	ModTimerType_Song = 2,
	ModTimerType_Default = 3,
}

---@enum (key) Month
Month = {
	Month_January = 0,
	Month_February = 1,
	Month_March = 2,
	Month_April = 3,
	Month_May = 4,
	Month_June = 5,
	Month_July = 6,
	Month_August = 7,
	Month_September = 8,
	Month_October = 9,
	Month_November = 10,
	Month_December = 11,
}

---@enum (key) MultiPlayer
MultiPlayer = {
	MultiPlayer_P1 = 0,
	MultiPlayer_P2 = 1,
	MultiPlayer_P3 = 2,
	MultiPlayer_P4 = 3,
	MultiPlayer_P5 = 4,
	MultiPlayer_P6 = 5,
	MultiPlayer_P7 = 6,
	MultiPlayer_P8 = 7,
	MultiPlayer_P9 = 8,
	MultiPlayer_P10 = 9,
	MultiPlayer_P11 = 10,
	MultiPlayer_P12 = 11,
	MultiPlayer_P13 = 12,
	MultiPlayer_P14 = 13,
	MultiPlayer_P15 = 14,
	MultiPlayer_P16 = 15,
	MultiPlayer_P17 = 16,
	MultiPlayer_P18 = 17,
	MultiPlayer_P19 = 18,
	MultiPlayer_P20 = 19,
	MultiPlayer_P21 = 20,
	MultiPlayer_P22 = 21,
	MultiPlayer_P23 = 22,
	MultiPlayer_P24 = 23,
	MultiPlayer_P25 = 24,
	MultiPlayer_P26 = 25,
	MultiPlayer_P27 = 26,
	MultiPlayer_P28 = 27,
	MultiPlayer_P29 = 28,
	MultiPlayer_P30 = 29,
	MultiPlayer_P31 = 30,
	MultiPlayer_P32 = 31,
}

---@enum (key) MusicWheelUsesSections
MusicWheelUsesSections = {
	MusicWheelUsesSections_Never = 0,
	MusicWheelUsesSections_Always = 1,
	MusicWheelUsesSections_ABCOnly = 2,
}

---@enum (key) NoteColorType
NoteColorType = {
	NoteColorType_Denominator = 0,
	NoteColorType_Progress = 1,
	NoteColorType_ProgressAlternate = 2,
}

---@enum (key) NoteColumnSplineMode
NoteColumnSplineMode = {
	NoteColumnSplineMode_Disabled = 0,
	NoteColumnSplineMode_Offset = 1,
	NoteColumnSplineMode_Position = 2,
}

---@enum (key) NotePart
NotePart = {
	NotePart_TapNote = 0,
	NotePart_TapMine = 1,
	NotePart_TapLift = 2,
	NotePart_TapFake = 3,
	NotePart_HoldHead = 4,
	NotePart_HoldTail = 5,
	NotePart_HoldTopCap = 6,
	NotePart_HoldBody = 7,
	NotePart_HoldBottomCap = 8,
}

---@enum (key) NoteType
NoteType = {
	NoteType_4th = 0,
	NoteType_8th = 1,
	NoteType_12th = 2,
	NoteType_16th = 3,
	NoteType_24th = 4,
	NoteType_32nd = 5,
	NoteType_48th = 6,
	NoteType_64th = 7,
	NoteType_192nd = 8,
}

---@enum (key) OptEffect
OptEffect = {
	OptEffect_SavePreferences = 0,
	OptEffect_ApplyGraphics = 1,
	OptEffect_ApplyTheme = 2,
	OptEffect_ChangeGame = 3,
	OptEffect_ApplySound = 4,
	OptEffect_ApplySong = 5,
	OptEffect_ApplyAspectRatio = 6,
}

---@enum (key) PaneCategory
PaneCategory = {
	PaneCategory_NumSteps = 0,
	PaneCategory_Jumps = 1,
	PaneCategory_Holds = 2,
	PaneCategory_Rolls = 3,
	PaneCategory_Mines = 4,
	PaneCategory_Hands = 5,
	PaneCategory_Lifts = 6,
	PaneCategory_Fakes = 7,
	PaneCategory_MachineHighScore = 8,
	PaneCategory_MachineHighName = 9,
	PaneCategory_ProfileHighScore = 10,
}

---@enum (key) PeakComboAward
PeakComboAward = {
	PeakComboAward_1000 = 0,
	PeakComboAward_2000 = 1,
	PeakComboAward_3000 = 2,
	PeakComboAward_4000 = 3,
	PeakComboAward_5000 = 4,
	PeakComboAward_6000 = 5,
	PeakComboAward_7000 = 6,
	PeakComboAward_8000 = 7,
	PeakComboAward_9000 = 8,
	PeakComboAward_10000 = 9,
}

---@enum (key) PlayMode
PlayMode = {
	PlayMode_Regular = 0,
	PlayMode_Nonstop = 1,
	PlayMode_Oni = 2,
	PlayMode_Endless = 3,
	PlayMode_Battle = 4,
	PlayMode_Rave = 5,
}

---@enum (key) PlayerController
PlayerController = {
	PlayerController_Human = 0,
	PlayerController_Autoplay = 1,
	PlayerController_Cpu = 2,
}

---@enum (key) PlayerNumber
PlayerNumber = {
	PlayerNumber_P1 = "PlayerNumber_P1",
	PlayerNumber_P2 = "PlayerNumber_P2"
}

---@enum (key) PolygonMode
PolygonMode = {
	PolygonMode_Fill = 0,
	PolygonMode_Line = 1,
	PolygonMode_Point = 2,
}

---@enum (key) Premium
Premium = {
	Premium_Off = 0,
	Premium_DoubleFor1Credit = 1,
	Premium_2PlayersFor1Credit = 2,
	Premium_1PBothAtOnceFor1Credit = 3,
}

---@enum (key) ProfileSlot
ProfileSlot = {
	ProfileSlot_Player1 = 0,
	ProfileSlot_Player2 = 1,
	ProfileSlot_Machine = 2,
}

---@enum (key) ProfileType
ProfileType = {
	ProfileType_Guest = 0,
	ProfileType_Normal = 1,
	ProfileType_Test = 2,
}

---@enum (key) RadarCategory
RadarCategory = {
	RadarCategory_Stream = 0,
	RadarCategory_Voltage = 1,
	RadarCategory_Air = 2,
	RadarCategory_Freeze = 3,
	RadarCategory_Chaos = 4,
	RadarCategory_TapsAndHolds = 5,
	RadarCategory_Jumps = 6,
	RadarCategory_Holds = 7,
	RadarCategory_Mines = 8,
	RadarCategory_Hands = 9,
	RadarCategory_Rolls = 10,
	RadarCategory_Lifts = 11,
	RadarCategory_Fakes = 12,
}

---@enum (key) RandomBackgroundMode
RandomBackgroundMode = {
	RandomBackgroundMode_Off = 0,
	RandomBackgroundMode_Animations = 1,
	RandomBackgroundMode_RandomMovies = 2,
}

---@enum (key) RankingCategory
RankingCategory = {
	RankingCategory_a = 0,
	RankingCategory_b = 1,
	RankingCategory_c = 2,
	RankingCategory_d = 3,
}

---@enum (key) RankingType
RankingType = {
	RankingType_Category = 0,
	RankingType_Course = 1,
}

---@enum (key) ReloadChanged
ReloadChanged = {
	ReloadChanged_None = 0,
	ReloadChanged_Enabled = 1,
	ReloadChanged_All = 2,
}

---@enum (key) SampleMusicPreviewMode
SampleMusicPreviewMode = {
	SampleMusicPreviewMode_Normal = 0,
	SampleMusicPreviewMode_StartToPreview = 1,
	SampleMusicPreviewMode_ScreenMusic = 2,
	SampleMusicPreviewMode_LastSong = 3,
	SampleMusicPreviewMode_Continuous = 4,
}

---@enum (key) ScreenType
ScreenType = {
	ScreenType_Attract = 0,
	ScreenType_GameMenu = 1,
	ScreenType_Gameplay = 2,
	ScreenType_SystemMenu = 3,
}

---@enum (key) SelectType
SelectType = {
	SelectType_SelectOne = 0,
	SelectType_SelectMultiple = 1,
	SelectType_SelectNone = 2,
}

---@enum (key) ShowDancingCharacters
ShowDancingCharacters = {
	ShowDancingCharacters_Off = 0,
	ShowDancingCharacters_Random = 1,
	ShowDancingCharacters_Select = 2,
}

---@enum (key) SortOrder
SortOrder = {
	SortOrder_Preferred = 0,
	SortOrder_Group = 1,
	SortOrder_Title = 2,
	SortOrder_BPM = 3,
	SortOrder_Popularity = 4,
	SortOrder_TopGrades = 5,
	SortOrder_Artist = 6,
	SortOrder_Genre = 7,
	SortOrder_BeginnerMeter = 8,
	SortOrder_EasyMeter = 9,
	SortOrder_MediumMeter = 10,
	SortOrder_HardMeter = 11,
	SortOrder_ChallengeMeter = 12,
	SortOrder_DoubleEasyMeter = 13,
	SortOrder_DoubleMediumMeter = 14,
	SortOrder_DoubleHardMeter = 15,
	SortOrder_DoubleChallengeMeter = 16,
	SortOrder_ModeMenu = 17,
	SortOrder_AllCourses = 18,
	SortOrder_Nonstop = 19,
	SortOrder_Oni = 20,
	SortOrder_Endless = 21,
	SortOrder_Length = 22,
	SortOrder_Roulette = 23,
	SortOrder_Recent = 24,
}

---@enum (key) SoundEffectType
SoundEffectType = {
	SoundEffectType_Off = 0,
	SoundEffectType_Speed = 1,
	SoundEffectType_Pitch = 2,
	SoundEffectType_Both = 3,
}

---@enum (key) Stage
Stage = {
	Stage_No = 0,
	Stage_1st = 1,
	Stage_2nd = 2,
	Stage_3rd = 3,
	Stage_4th = 4,
	Stage_5th = 5,
	Stage_6th = 6,
	Stage_Next = 7,
	Stage_Final = 8,
	Stage_Extra1 = 9,
	Stage_Extra2 = 10,
	Stage_Nonstop = 11,
	Stage_Oni = 12,
	Stage_Endless = 13,
	Stage_Event = 14,
	Stage_Demo = 15,
}

---@enum (key) StageAward
StageAward = {
	StageAward_FullComboW3 = 0,
	StageAward_SingleDigitW3 = 1,
	StageAward_OneW3 = 2,
	StageAward_FullComboW2 = 3,
	StageAward_SingleDigitW2 = 4,
	StageAward_OneW2 = 5,
	StageAward_FullComboW1 = 6,
	StageAward_80PercentW3 = 7,
	StageAward_90PercentW3 = 8,
	StageAward_100PercentW3 = 9,
}

---@enum (key) StageResult
StageResult = {
	StageResult_Win = 0,
	StageResult_Lose = 1,
	StageResult_Draw = 2,
}

---@enum (key) StepsType
StepsType = {
	StepsType_Dance_Single = 0,
	StepsType_Dance_Double = 1,
	StepsType_Dance_Couple = 2,
	StepsType_Dance_Solo = 3,
	StepsType_Dance_Threepanel = 4,
	StepsType_Dance_Routine = 5,
	StepsType_Pump_Single = 6,
	StepsType_Pump_Halfdouble = 7,
	StepsType_Pump_Double = 8,
	StepsType_Pump_Couple = 9,
	StepsType_Pump_Routine = 10,
	StepsType_Kb7_Single = 11,
	StepsType_Ez2_Single = 12,
	StepsType_Ez2_Double = 13,
	StepsType_Ez2_Real = 14,
	StepsType_Para_Single = 15,
	StepsType_Para_Double = 16,
	StepsType_Para_Eight = 17,
	StepsType_Ds3ddx_Single = 18,
	StepsType_Bm_Single5 = 19,
	StepsType_Bm_Double5 = 20,
	StepsType_Bm_Single7 = 21,
	StepsType_Bm_Double7 = 22,
	StepsType_Maniax_Single = 23,
	StepsType_Maniax_Double = 24,
	StepsType_Techno_Single4 = 25,
	StepsType_Techno_Single5 = 26,
	StepsType_Techno_Single8 = 27,
	StepsType_Techno_Single9 = 28,
	StepsType_Techno_Double4 = 29,
	StepsType_Techno_Double5 = 30,
	StepsType_Techno_Double8 = 31,
	StepsType_Techno_Double9 = 32,
	StepsType_Pnm_Three = 33,
	StepsType_Pnm_Four = 34,
	StepsType_Pnm_Five = 35,
	StepsType_Pnm_Seven = 36,
	StepsType_Pnm_Nine = 37,
	StepsType_Pnm_Nine_Double = 38,
	StepsType_Gddm_Real = 39,
	StepsType_Gddm_New = 40,
	StepsType_Gddm_Old = 41,
	StepsType_Guitar_Five = 42,
	StepsType_Bass_Six = 43,
	StepsType_Guitar_Six = 44,
	StepsType_Guitar_Three = 45,
	StepsType_Bass_Four = 46,
	StepsType_Gh_Solo = 47,
	StepsType_Gh_Solo6 = 48,
	StepsType_Gh_Bass = 49,
	StepsType_Gh_Bass6 = 50,
	StepsType_Gh_Rhythm = 51,
	StepsType_Gh_Rhythm6 = 52,
	StepsType_Taiko = 53,
	StepsType_Lights_Cabinet = 54,
	StepsType_Kickbox_Human = 55,
	StepsType_Kickbox_Quadarm = 56,
	StepsType_Kickbox_Insect = 57,
	StepsType_Kickbox_Arachnid = 58,
}

---@enum (key) StyleType
StyleType = {
	StyleType_OnePlayerOneSide = 0,
	StyleType_TwoPlayersTwoSides = 1,
	StyleType_OnePlayerTwoSides = 2,
	StyleType_TwoPlayersSharedSides = 3,
}

---@enum (key) TapNoteScore
TapNoteScore = {
	TapNoteScore_None = 0,
	TapNoteScore_HitMine = 1,
	TapNoteScore_AvoidMine = 2,
	TapNoteScore_CheckpointMiss = 3,
	TapNoteScore_Miss = 4,
	TapNoteScore_W5 = 5,
	TapNoteScore_W4 = 6,
	TapNoteScore_W3 = 7,
	TapNoteScore_W2 = 8,
	TapNoteScore_W1 = 9,
	TapNoteScore_ProW5 = 10,
	TapNoteScore_ProW4 = 11,
	TapNoteScore_ProW3 = 12,
	TapNoteScore_ProW2 = 13,
	TapNoteScore_ProW1 = 14,
	TapNoteScore_MaxScore = 15,
	TapNoteScore_CheckpointHit = 16,
}

---@enum (key) TapNoteScoreJudgeType
TapNoteScoreJudgeType = {
	TapNoteScoreJudgeType_MinimumScore = 0,
	TapNoteScoreJudgeType_LastScore = 1,
}

---@enum (key) TapNoteType
TapNoteType = {
	TapNoteType_Empty = 0,
	TapNoteType_Tap = 1,
	TapNoteType_HoldHead = 2,
	TapNoteType_HoldTail = 3,
	TapNoteType_Mine = 4,
	TapNoteType_Lift = 5,
	TapNoteType_Attack = 6,
	TapNoteType_AutoKeysound = 7,
	TapNoteType_Fake = 8,
}

---@enum (key) TapNoteSubType
TapNoteSubType = {
	TapNoteSubType_Hold = 0,
	TapNoteSubType_Roll = 1,
}
---@enum (key) TapNoteSource
TapNoteSource = {
	TapNoteSource_Original = 0,
	TapNoteSource_Addition = 1,
}
---@enum (key) TextGlowMode
TextGlowMode = {
	TextGlowMode_Inner = 0,
	TextGlowMode_Stroke = 1,
	TextGlowMode_Both = 2,
}
---@enum (key) TextureMode
TextureMode = {
	TextureMode_Modulate = 0,
	TextureMode_Glow = 1,
	TextureMode_Add = 2,
}
---@enum (key) TweenType
TweenType = {
	TweenType_Linear = 0,
	TweenType_Accelerate = 1,
	TweenType_Decelerate = 2,
	TweenType_Spring = 3,
	TweenType_Smooth = 4,
	TweenType_BounceBegin = 5,
	TweenType_BounceEnd = 6,
	TweenType_Bezier = 7,
	TweenType_Bezier8D = 9,
	TweenType_Step = 10,
	TweenType_SmoothStep = 11,
	TweenType_EaseInSine = 12,
	TweenType_EaseOutSine = 13,
	TweenType_EaseInOutSine = 14,
	TweenType_EaseOutInSine = 15,
	TweenType_EaseInQuad = 16,
	TweenType_EaseOutQuad = 17,
	TweenType_EaseInOutQuad = 18,
	TweenType_EaseOutInQuad = 19,
	TweenType_EaseInCubic = 20,
	TweenType_EaseOutCubic = 21,
	TweenType_EaseInOutCubic = 22,
	TweenType_EaseOutInCubic = 23,
	TweenType_EaseInQuart = 24,
	TweenType_EaseOutQuart = 25,
	TweenType_EaseInOutQuart = 26,
	TweenType_EaseOutInQuart = 27,
	TweenType_EaseInQuint = 28,
	TweenType_EaseOutQuint = 29,
	TweenType_EaseInOutQuint = 30,
	TweenType_EaseOutInQuint = 31,
	TweenType_EaseInExpo = 32,
	TweenType_EaseOutExpo = 33,
	TweenType_EaseInOutExpo = 34,
	TweenType_EaseOutInExpo = 35,
	TweenType_EaseInBack = 36,
	TweenType_EaseOutBack = 37,
	TweenType_EaseInOutBack = 38,
	TweenType_EaseOutInBack = 39,
	TweenType_EaseInBackEx = 40,
	TweenType_EaseOutBackEx = 41,
	TweenType_EaseInOutBackEx = 42,
	TweenType_EaseOutInBackEx = 43,
	TweenType_EaseInCircle = 44,
	TweenType_EaseOutCircle = 45,
	TweenType_EaseInOutCircle = 46,
	TweenType_EaseOutInCircle = 47,
	TweenType_EaseInElastic = 48,
	TweenType_EaseOutElastic = 49,
	TweenType_EaseInOutElastic = 50,
	TweenType_EaseOutInElastic = 51,
	TweenType_EaseInElasticEx = 52,
	TweenType_EaseOutElasticEx = 53,
	TweenType_EaseInOutElasticEx = 54,
	TweenType_EaseOutInElasticEx = 55,
	TweenType_EaseInBounce = 56,
	TweenType_EaseOutBounce = 57,
	TweenType_EaseInOutBounce = 58,
	TweenType_EaseOutInBounce = 59,
}
---@enum (key) UnlockRequirement
UnlockRequirement = {
	UnlockRequirement_ArcadePoints = 0,
	UnlockRequirement_DancePoints = 1,
	UnlockRequirement_SongPoints = 2,
	UnlockRequirement_ExtraCleared = 3,
	UnlockRequirement_ExtraFailed = 4,
	UnlockRequirement_Toasties = 5,
	UnlockRequirement_StagesCleared = 6,
	UnlockRequirement_NumberUnlocked = 7,
}
---@enum (key) UnlockRewardType
UnlockRewardType = {
	UnlockRewardType_Song = 0,
	UnlockRewardType_Steps = 1,
	UnlockRewardType_StepsType = 2,
	UnlockRewardType_Course = 3,
	UnlockRewardType_Modifier = 4,
}

--- Vertical alignment.
---@see Actor.vertalign
---@enum (key) VertAlign
VertAlign = {
	VertAlign_Top = 0,
	VertAlign_Middle = 1,
	VertAlign_Bottom = 2
}

---@enum (key) WheelItemDataType
WheelItemDataType = {
	WheelItemDataType_Generic = 0,
	WheelItemDataType_Section = 1,
	WheelItemDataType_Song = 2,
	WheelItemDataType_Roulette = 3,
	WheelItemDataType_Random = 4,
	WheelItemDataType_Portal = 5,
	WheelItemDataType_Course = 6,
	WheelItemDataType_Sort = 7,
	WheelItemDataType_Custom = 8,
}
---@enum (key) WheelState
WheelState = {
	WheelState_Selecting = 0,
	WheelState_FlyingOffBeforeNextSort = 1,
	WheelState_FlyingOnAfterNextSort = 2,
	WheelState_RouletteSpinning = 3,
	WheelState_RouletteSlowingDown = 4,
	WheelState_RandomSpinning = 5,
	WheelState_Locked = 6,
}
---@enum (key) ZTestMode
ZTestMode = {
	ZTestMode_Off = 0,
	ZTestMode_WriteOnPass = 1,
	ZTestMode_WriteOnFail = 2,
}

-- Convenience aliases:
---@type HorizAlign
left = "HorizAlign_Left"
---@type HorizAlign
center = "HorizAlign_Center"
---@type HorizAlign
right = "HorizAlign_Right"
---@type VertAlign
top = "VertAlign_Top"
---@type VertAlign
middle = "VertAlign_Middle"
---@type VertAlign
bottom = "VertAlign_Bottom"